package com.helios.patient.security;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;

import org.junit.jupiter.api.Test;

import tools.jackson.databind.json.JsonMapper;

class SessionProofCodecTest {

    private static final String SECRET = "helios-local-session-secret";

    @Test
    void createsAndVerifiesV1PatientSessionProof() {
        Clock clock = Clock.fixed(Instant.ofEpochSecond(1_700_000_000L), ZoneOffset.UTC);
        var codec = new SessionProofCodec(SECRET, 28_800, clock, JsonMapper.builder().build());

        String token = codec.create("c123456789012345678901234");
        var verification = codec.verify(token);

        // Exact vector generated by the existing TypeScript SignedTokenCodec.
        assertThat(token).isEqualTo(
                "v1.eyJzdWIiOiJjMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0Iiwia2luZCI6InBhdGllbnQtc2Vzc2lvbiIsImlhdCI6MTcwMDAwMDAwMCwiZXhwIjoxNzAwMDI4ODAwfQ.18d95fb4958dc5d43a94fae4806a86fc43677a53eaf57d284ca107971661b9f6");
        assertThat(verification.valid()).isTrue();
        assertThat(verification.expired()).isFalse();
        assertThat(verification.subject()).isEqualTo("c123456789012345678901234");
    }

    @Test
    void rejectsTamperedProof() {
        Clock clock = Clock.fixed(Instant.ofEpochSecond(1_700_000_000L), ZoneOffset.UTC);
        var codec = new SessionProofCodec(SECRET, 28_800, clock, JsonMapper.builder().build());
        String token = codec.create("c123456789012345678901234");

        var verification = codec.verify(token.substring(0, token.length() - 1) + "0");

        assertThat(verification.valid()).isFalse();
    }
}
