// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/doctor" | "/doctor-coming-soon" | "/doctor/login" | "/doctor/patients/[patientId]" | "/doctor/patients/[patientId]/ayush" | "/doctor/patients/[patientId]/brief" | "/doctor/queue" | "/doctor/sih-demo" | "/doctor/verification" | "/doctor/what-changed" | "/patient" | "/patient/complaint" | "/patient/complete" | "/patient/consent" | "/patient/details" | "/patient/documents" | "/patient/interview" | "/patient/language" | "/patient/listening" | "/patient/review" | "/patient/timeline" | "/patient/waiting" | "/sih-demo"
type PageRoutes = never
type LayoutRoutes = "/" | "/doctor" | "/patient"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/doctor": {}
  "/doctor-coming-soon": {}
  "/doctor/login": {}
  "/doctor/patients/[patientId]": { "patientId": string; }
  "/doctor/patients/[patientId]/ayush": { "patientId": string; }
  "/doctor/patients/[patientId]/brief": { "patientId": string; }
  "/doctor/queue": {}
  "/doctor/sih-demo": {}
  "/doctor/verification": {}
  "/doctor/what-changed": {}
  "/patient": {}
  "/patient/complaint": {}
  "/patient/complete": {}
  "/patient/consent": {}
  "/patient/details": {}
  "/patient/documents": {}
  "/patient/interview": {}
  "/patient/language": {}
  "/patient/listening": {}
  "/patient/review": {}
  "/patient/timeline": {}
  "/patient/waiting": {}
  "/sih-demo": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/doctor": never
  "/patient": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
