// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/doctor-coming-soon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor-coming-soon">> = Specific
  const handler = {} as typeof import("../../src/app/doctor-coming-soon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/doctor/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/login">> = Specific
  const handler = {} as typeof import("../../src/app/doctor/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/doctor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor">> = Specific
  const handler = {} as typeof import("../../src/app/doctor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/doctor/patients/[patientId]/ayush/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/patients/[patientId]/ayush">> = Specific
  const handler = {} as typeof import("../../src/app/doctor/patients/[patientId]/ayush/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/doctor/patients/[patientId]/brief/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/patients/[patientId]/brief">> = Specific
  const handler = {} as typeof import("../../src/app/doctor/patients/[patientId]/brief/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/doctor/patients/[patientId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/patients/[patientId]">> = Specific
  const handler = {} as typeof import("../../src/app/doctor/patients/[patientId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/doctor/queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/queue">> = Specific
  const handler = {} as typeof import("../../src/app/doctor/queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/doctor/sih-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/sih-demo">> = Specific
  const handler = {} as typeof import("../../src/app/doctor/sih-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/doctor/verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/verification">> = Specific
  const handler = {} as typeof import("../../src/app/doctor/verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/doctor/what-changed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/what-changed">> = Specific
  const handler = {} as typeof import("../../src/app/doctor/what-changed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/patient/complaint/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/complaint">> = Specific
  const handler = {} as typeof import("../../src/app/patient/complaint/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/patient/complete/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/complete">> = Specific
  const handler = {} as typeof import("../../src/app/patient/complete/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/patient/consent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/consent">> = Specific
  const handler = {} as typeof import("../../src/app/patient/consent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/patient/details/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/details">> = Specific
  const handler = {} as typeof import("../../src/app/patient/details/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/patient/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/documents">> = Specific
  const handler = {} as typeof import("../../src/app/patient/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/patient/interview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/interview">> = Specific
  const handler = {} as typeof import("../../src/app/patient/interview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/patient/language/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/language">> = Specific
  const handler = {} as typeof import("../../src/app/patient/language/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/patient/listening/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/listening">> = Specific
  const handler = {} as typeof import("../../src/app/patient/listening/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/patient/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient">> = Specific
  const handler = {} as typeof import("../../src/app/patient/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/patient/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/review">> = Specific
  const handler = {} as typeof import("../../src/app/patient/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/patient/timeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/timeline">> = Specific
  const handler = {} as typeof import("../../src/app/patient/timeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/patient/waiting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/waiting">> = Specific
  const handler = {} as typeof import("../../src/app/patient/waiting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sih-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sih-demo">> = Specific
  const handler = {} as typeof import("../../src/app/sih-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/doctor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/doctor">> = Specific
  const handler = {} as typeof import("../../src/app/doctor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/patient/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/patient">> = Specific
  const handler = {} as typeof import("../../src/app/patient/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
