ALTER TYPE "VerificationFactType" ADD VALUE IF NOT EXISTS 'LIVE_INTAKE_FACT';
ALTER TABLE "HeliosIntakeFact"
  ADD COLUMN IF NOT EXISTS "verificationStatus" "VerificationStatus" NOT NULL DEFAULT 'PATIENT_REPORTED',
  ADD COLUMN IF NOT EXISTS "verificationVersion" INTEGER NOT NULL DEFAULT 0;
