package com.helios.patient.intake;

public enum VerificationStatus {
    PENDING, VERIFIED, PARTIALLY_CORRECT, EDITED, REJECTED, MISSED, UNREVIEWED,
    PATIENT_REPORTED, AI_STRUCTURED, DOCUMENT_EXTRACTED, NEEDS_REVIEW,
    DOCTOR_VERIFIED, DOCTOR_CORRECTED, DOCTOR_REJECTED, SUPERSEDED
}
