{
 "title": "Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(service_name)" },
   { "name": "level", "label": "Level", "query": "label_values(level)" },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"docker\", service_name=~\"$service\", level=~\"$level\"} |= \"$search\" [$__interval])) by (service_name, level)",
     "legendFormat": "{{service_name}} {{level}}"
    }
   ]
  },
  {
   "title": "Errors Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"docker\", service_name=~\"$service\", level=~\"(?i)error\"} |= \"$search\" [$__range]))"
    }
   ]
  },
  {
   "title": "Warnings Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"docker\", service_name=~\"$service\", level=~\"(?i)warn.*\"} |= \"$search\" [$__range]))"
    }
   ]
  },
  {
   "title": "Logs Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"docker\", service_name=~\"$service\"} |= \"$search\" [$__range]))"
    }
   ]
  },
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "Please use filters above to select services, log levels, search query or time period for displayed logs. You may also want to disable auto-refresh in the top right corner so that the panel stops scrolling the logs. To export logs that you see, click the `Logs` panel, type `i` and then click the `Download logs` button. You may also copy a single log line by clicking on it and then the copy icon."
   }
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"docker\", service_name=~\"$service\", level=~\"$level\"} |= \"$search\""
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{job=\"docker\", service_name=~\"$service\", level=~\"(?i)error\"} |= \"$search\""
    }
   ]
  }
 ]
}